### ISSUE TITLE
Discussion - Can the Cupcake website live on Bluemix?

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#100]
> As a Cupcake website designer,

> I need to know where will be the best place for the Cupcake website to be set up 

> so that I can protect the intellectual priority type of information from the none-IBM.com adopters and IBMers.

#### Additional information
- Wonil suggested having the website inside of the Bluemix

#### Task
- Discuss with Wonil and Jeff to find out if Bluemix is the best place for the Cupcake website to live based on the conditions we have.

#### Acceptance criteria
- [ ] Outcome accepted by Linda
- [ ] Share the updated outcome with our team

**Comment by JennySanchez** [comment]
List this discussion on the December 3rd [Team Huddle agenda](https://ibm.box.com/s/g3bpwxwyknpqldhg8uxfv2n5hka1rvi5).

**Comment by jeffchew** [comment]
@JennySanchez @wonilsuhibm @ljcarot We could host it up on bluemix, though we would need to think of the hosting cost in IBM Cloud. Also, would we stay as bluemix, or would we have it under something in www.ibm.com? If the latter, we may not need bluemix and just upload directly to the EI server.

**Comment by wonilsuhibm** [comment]
@jeffchew considering that this is a closed release to a very small audience, bluemix domain is fine to me.

**Comment by ljcarot** [comment]
Why do we need special hosting environment?

**Comment by jeffchew** [comment]
We discussed this in Huddle on 12/4/2019, and decided to go with Netlify. URL has been changed to:

https://carbon-for-ibmdotcom.netlify.com/

**Comment by JennySanchez** [comment]
Perfect. Thanks @jeffchew !
