### ISSUE TITLE
Finalize Patterns section IA for the Cupcake website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#101]
> As a Cupcake website creator, 

> I need a clear IA direction for presenting the pattern information

> so that our adopter can find the information efficiently.

#### Additional information
- Define Patterns section IA for the Cupcake website includes:

1. Find out what groups of patterns we have?
2. What patterns are included in each group?
3. How the IA works based on the answers of 1 and 2.

- Collaborate with Lara on the IA.

#### Acceptance criteria
- [ ] IA agreed by Wonil and Scott.

**Comment by JennySanchez** [comment]
@larahanlon2 

I created this issue for us to record the outcome form our conversation today and make sure we finalized on the IA for the Pattern section.

Can you share the latest IA structure and patter list you have here whenever you have a minute?

**Comment by JennySanchez** [comment]
FYI - @wonilsuhibm @ScottBokma

**Comment by larahanlon2** [comment]
Met with Jenny, Wonil, Jacob and Scott today. Presented 8 options for `patterns` IA and agreed on the following as the first step:

![patterns--IA--cupcake](https://user-images.githubusercontent.com/53093550/69668974-f153e980-105e-11ea-8d3b-c0c2324ed721.png)
![patterns--IA--wedding](https://user-images.githubusercontent.com/53093550/69668975-f153e980-105e-11ea-95dc-1ad957fa96ad.png)

**Comment by JennySanchez** [comment]
Looking good and thank you for confirming @larahanlon2.

**Comment by JennySanchez** [comment]
We updated the left nav to match the outcome, this task is completed.
