### ISSUE TITLE
Cupcake website page creation - Components/Masthead page

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-website#14]
@JennySanchez commented on [Fri Oct 18 2019](https://github.com/carbon-design-system/ibm-dotcom-library/issues/542)

#### User Story

> As an IBM.com page creator

> I need to: have a good understanding of the masthead component

> so that I can: do my day to day work without confusion.

#### Additional information
- Please make sure the content draft and all work documents are saved in the `Cupcake Website - Design + Content` folder.
- Carbon UI shell information can be viewed [here](https://www.carbondesignsystem.com/components/UI-shell-header/usage)
- Make sure we follow the [component content template](https://ibm.box.com/s/arlqd8wg4l2a0yy9fvsneagvs1f8rgfy) from the carbon team but take out the "General guidance" section title at the beginning of the page.

#### Task
- Collaborate with @ScottBokma  for the content creation.

#### Acceptance criteria
- [ ] Content and design created and reviewed with the stream lead, the developer and Wonil.
- [ ] Content and design accepted by Wonil and Linda.

**Comment by jacobottesen-dgc** [comment]
@ScottBokma I've started putting together the content for the masthead page. Could you review the content I have so far? I'll be adding to it next week.

**Comment by ScottBokma** [comment]
@jacobottesen-dgc I can't get to the folder for review. I might need to be added, as the message I'm getting is "This shared file or folder link has been removed or is unavailable to you."

**Comment by jacobottesen-dgc** [comment]
@ScottBokma @larahanlon2 I've made a few updates to the Masthead cupcake content. Can you both take one last look at it? If you have changes or want anything removed please add your notes in purple. Thanks for the help!
Boxnote link: https://ibm.box.com/s/n0hh9f4h493kvmdrdrf97pu6ryzg915c

**Comment by jacobottesen-dgc** [comment]
@jimpistilli Please review the masthead content rough draft. Thanks!
https://ibm.ent.box.com/notes/542712355171

**Comment by JennySanchez** [comment]
@jacobottesen-dgc @jimpistilli Can you double-check the document links? Let's make sure we save everything in the Cupcake Website - Design + Content folder, please.

https://ibm.ent.box.com/notes/542712355171 - I can not view the content with the link.
https://ibm.box.com/s/os8sf0cxgiodoby43yp1jn1eo27kk1i0 - I did not see any red text and not sure if I missed anything?

**Comment by jimpistilli** [comment]
@JennySanchez @jacobottesen-dgc Sorry, uploaded not the most recent version to box. It's there now (https://ibm.ent.box.com/file/549418850205) - I suggest downloading and viewing changes in Word over previewing on Box.

@jacobottesen-dg: The other Box note link that Jenny specified does not work for me either

**Comment by jimpistilli** [comment]
@JennySanchez @jacobottesen-dgc Hey there - checking in if this one is done or still there is editing outstanding? Most recent version of copy here: https://ibm.ent.box.com/file/549418850205

**Comment by JennySanchez** [comment]
Content created and can be viewed [here](https://carbon-for-ibm.netlify.com/components/masthead).

@jacobottesen-dgc FYI: The Masthead content update issue is created as #60.
