### ISSUE TITLE
Cupcake website page creation - Guidelines/Overview page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#15]
#### User Story

> As an IBM.com page creator

> I need to: have a good understanding of the guidelines

> so that I can: do my day to day work without confusion.

#### Additional information
✏️ Carbon and DDS v19a websites do not have Guideline overview pages so the content will be new. Please take a look at all the overview pages across the updated sitemap below and come up with a structure for all the overview pages, so we can keep consistency.

#### Acceptance criteria
- [ ] Content and design published with markdowns.
- [ ] Content and design reviewed with Jenny and Wonil.
- [ ] Content and design accepted by Wonil and Linda.

**Comment by JennySanchez** [comment]
As we pivot to the new Cupcake website structure, we will no longer create the Guideline/Layout page. Instead, we will modify this issue for the Guideline/Overview page content creation.

FYI - @RobertaJHahn

**Comment by JennySanchez** [comment]
@jimpistilli The super rough draft of the content copy is ready for your edit and can be viewed in the box folder [here](https://ibm.box.com/s/ja84ih7uod29soymx5lbz0gmxof088ut).

Let's hop on WebEx and let me go over the content with you before you start. Calendar invite coming soon.

**Comment by jimpistilli** [comment]
@JennySanchez @jacobottesen-dgc Updated version here: https://ibm.ent.box.com/file/560544800441?sb=/activity

**Comment by JennySanchez** [comment]
@jimpistilli I reviewed and added my comments to the document. Let me know if you have any questions.

**Comment by jimpistilli** [comment]
@JennySanchez Updated version below, reflecting your comments.  Please let me know if anything additional is needed.

https://ibm.box.com/s/zdoe49xt24tf8k8lgs1v9hr3afj44jq3

cc: @jacobottesen-dgc

**Comment by JennySanchez** [comment]
Thank you, @jimpistilli. I will publish the content with markdowns as the next step.

**Comment by JennySanchez** [comment]
Page published with markdowns and can be viewed [here](https://carbon-for-ibm.netlify.com/guidelines/).

**Comment by jimpistilli** [comment]
@JennySanchez Looks great! Can I make minor edit requests?  If so:

- Expressive Theme should be in _italics_

- "colloquial natural language" should have a , after colloquial 

- The link (and all links really) should be opening in a new page instead of using the same browser. This is a best practice we try to employ for our marketing pages and I believe should carry over here as well. It's a best practice for a better user experience, and keeps readers on our page longer. 


cc: @jacobottesen-dgc
