### ISSUE TITLE
Cupcake website page creation - Components/Footer page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#16]
#### User Story

> As an IBM.com page creator

> I need to: have a good understanding of the footer component

> so that I can: do my day to day work without confusion.

#### Additional information
- Cupcake website page development priority can be viewed via #1664.
- Footer on the v19a website can be viewed [here](https://www.ibm.com/standards/web/components/footer/)
- Make sure we follow the [component content template](https://ibm.box.com/s/arlqd8wg4l2a0yy9fvsneagvs1f8rgfy) from the carbon team but take out the "General guidance" section title at the beginning of the page.

#### Task
- Collaborate with @ScottBokma  for the content creation.

#### Acceptance criteria
- [ ] Content and design created and reviewed with the stream lead, the developer and Wonil.
- [ ] Shared with the Carbon and IDL team for feedback.
- [ ] Content and design accepted by Wonil and Linda.
- [ ] Create the page with markdowns as the next step.

**Comment by jacobottesen-dgc** [comment]
Hey @JennySanchez I have a rough draft for the Footer. Could you review it and let me know if I need to change anything?

https://ibm.box.com/s/3sgu496ybtm858c21bqz56icfb6qz71h

cc @ScottBokma

**Comment by jacobottesen-dgc** [comment]
@JennySanchez Scott as mentioned that we will need to make changes to this page when locale selector is finalized. 

cc @ScottBokma

**Comment by jacobottesen-dgc** [comment]
Hey @jimpistilli can you review the content for the footer page?

https://ibm.ent.box.com/notes/549525475269

**Comment by jimpistilli** [comment]
Edited version here: https://ibm.box.com/s/rqxf7dfdhshltydp130kr5kfnlo4afr7

cc: @JennySanchez @jacobottesen-dgc

**Comment by jacobottesen-dgc** [comment]
@JennySanchez Just to clarify. I should not have the locale selector on the footer for the cupcake site?

cc. @jeffchew

**Comment by JennySanchez** [comment]
@jacobottesen-dgc FYI: on the content update issue is created as #60.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc The locale selector on the footer should be worked on by @jeffchew via issue #29. Can you add task detail to issue 29?
