### ISSUE TITLE
Cupcake website page creation - Components/Checkbox page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#17]
@JennySanchez commented on [Fri Oct 18 2019](https://github.com/carbon-design-system/ibm-dotcom-library/issues/544)

#### User Story

> As an IBM.com page creator

> I need to: have a good understanding of the checkbox component

> so that I can: do my day to day work without confusion.

#### Additional information
- Cupcake website page development priority can be viewed via #1664.
- Make sure we follow the [component content template](https://ibm.box.com/s/arlqd8wg4l2a0yy9fvsneagvs1f8rgfy) from the carbon team but take out the "General guidance" section title at the beginning of the page.

#### Task
- Collaborate with @oliviaflory for the content creation.

#### Acceptance criteria
- [ ] Content and design created and reviewed with the stream lead, the developer and Wonil.
- [ ] Shared with the Carbon and IDL team for feedback.
- [ ] Content and design accepted by Wonil and Linda.
- [ ] Create the page with markdowns as the next step.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Can you save the content work file in the BOX folder and provide the link to it here?

**Comment by jacobottesen-dgc** [comment]
@JennySanchez Yes, here is the the box note link: https://ibm.box.com/s/s8h0d5zjb5j0iv7hvwc6z2hx2n53wfzy

**Comment by JennySanchez** [comment]
@jimpistilli This is not related to #14.

**Comment by JennySanchez** [comment]
As we pivot to the new Cupcake website structure, we will no longer work on the Checkbox page, the current content from Jacob will be saved in the BOX folder for future use if we decide to add the Checkbox page in the future.
