### ISSUE TITLE
Cupcake website page creation - Get started/Overview page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#18]
#### User Story

> As an IBM.com page creator

> I need to: know where to find help resources

> so that I can: do my day to day work efficiently.

#### Additional information
- Cupcake website page development priority can be viewed via #1664.
- The Get started/Overview page on the Carbon Design website can be viewed [here](https://www.carbondesignsystem.com/get-started/about-carbon)
- The Get started/Overview on the current v19a website can be viewed [here](https://www.ibm.com/standards/web/getting-started/about.html)

#### Task
- Collaborate with @wonilsuhibm for the content creation.

#### Acceptance criteria
- [ ] Content and design created and reviewed with Jenny and Wonil.
- [ ] Content and design accepted by Wonil and Linda.

**Comment by jacobottesen-dgc** [comment]
Hey @JennySanchez I have a rough draft for the overview page. Could you take a look? 

https://ibm.box.com/s/swpiqo3z4iy00kzc411y37aw0w8eilew

**Comment by JennySanchez** [comment]
@jacobottesen-dgc I can not open the link. Can you make sure the file is saved in the `Cupcake Website folder` then share the link here? Thanks.

**Comment by jacobottesen-dgc** [comment]
@jimpistilli Hey Jim! Could you review the content for this page? 

https://ibm.ent.box.com/notes/549530021915

**Comment by JennySanchez** [comment]
Page content completed and can be viewed [here](https://carbon-for-ibm.netlify.com/getting-started). One enhancement we need to do is update the "Introduction" session. The task issue for the enhancement is created as #59.
