### ISSUE TITLE
Set up Cupcake website IA based on the updated sitemap

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#25]
#### User story:
> 
As a Digital Design System Cupcake website creator

> 
I need to see the correct overall elements are such as the site title, footer, navigation, etc.

> 
so that I can focus on the content creation and work efficiently.

#### Additional information

- The current Gatsby theme for the Cupcake website can be viewed [here](https://carbon-for-ibm.netlify.com/)
 
#### Deliverables

- The overall elements for the Cupcake website are updated and ready for content implementation.

**Comment by JennySanchez** [comment]
@jeffchew As mentioned in our training session today, it will be great if I can have a dev set up the website navigation so Jacob and I can focus on the content and not worry about the website structure set up. Please let me know if this is still doable for Sprint 21?

**Comment by JennySanchez** [comment]
**Updated sitemap:**
![Cupacke sitemap v2 0](https://user-images.githubusercontent.com/45213839/67964259-f6dc2200-fbcd-11e9-9540-5248be3f5fb1.jpg)

**Comment by JennySanchez** [comment]
@jeffchew The review/PR was approved last week. Anything else I need to do for you?

**Comment by jeffchew** [comment]
@JennySanchez don't think so, I think we're good!

**Comment by JennySanchez** [comment]
Perfect. Thanks, Jeff!
