### ISSUE TITLE
Set up the overall Cupcake website elements

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#29]
#### User story:
> 
As a Digital Design System Cupcake website adopter

> 
I need to see the correct left-hand Github and Carbon Design System links, right-hand mini menu, on-page navigation, and footer link set ups

> 
so that I can be taken to the proper places to get the information I need without confusion.

#### Additional information

The current Gatsby theme for the Cupcake website can be viewed [here](https://carbon-for-ibm.netlify.com/)

This task contains the following  areas:

1. The website title - It should say "Carbon for IBM.com"?
![Screen Shot 2019-11-12 at 10 27 33 AM](https://user-images.githubusercontent.com/45213839/68690135-2298c980-0537-11ea-9610-27ae7f5d226f.png)

2. Left-hand Github and Carbon Design System links
![Screen Shot 2019-10-31 at 1 29 56 PM](https://user-images.githubusercontent.com/45213839/67975674-90adca00-fbe2-11e9-9f3b-388634fed7cc.png)

3. Right-hand mini menu
![Screen Shot 2019-10-31 at 11.35.19 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/200645dd-0662-4c7b-81c5-c1b93ba16b95)

4. On-page navigation
![Screen Shot 2019-10-31 at 11.50.23 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/2ab51312-615d-4eb0-8a65-dbbfab697d45)

5. Footer
 ![Screen Shot 2019-10-31 at 11.50.33 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/a637afb5-f745-43c2-8119-6092727b4d7d)

#### Acceptance criteria

- [ ] All four items listed above set up completed and linked to the correct places and review with Jenny.

**Comment by jeffchew** [comment]
@JennySanchez do you have the URLs that these need to go to?

**Comment by JennySanchez** [comment]
@jeffchew No, but I can create a list.

**Comment by JennySanchez** [comment]
**For item 1:**
Confirmed with Linda, we will say "Carbon for IBM.com" and it will take the website visitor back to the homepage.

**For item 2:**
Github: https://github.com/carbon-design-system/ibm-dotcom-library
Carbon Design System: https://www.carbondesignsystem.com/

**For item 3:**
IBM Design: https://www.ibm.com/design/
IBM Design Language: https://www.ibm.com/design/language/
IBM Brand Center: https://www.ibm.com/brand/
IBM Carbon Design System: https://www.carbondesignsystem.com/
IBM Design Research: http://www.research.ibm.com/
Enterprise Design Thinking: https://www.ibm.com/design/thinking/
IBM iX: https://www.ibm.com/services/ibmix/
IBM Journey System: (Coming soon - working on this with Sarah)
IBM Accessibility:https://w3.ibm.com/able/

**For item 5:**
Email: ibmdigitaldesign@us.ibm.com
Github: https://github.com/carbon-design-system/ibm-dotcom-library

**Comment by JennySanchez** [comment]
@jeffchew  For the IBM Journey System link, Sarah is working on creating a Journey System site off of the IBM Design website as a practice. The development should start in December so we won't know the URL till then. If it helps, let's take the link off the website for now.

**Comment by JennySanchez** [comment]
PR Approved!
