### ISSUE TITLE
Cupcake website page creation - Patterns/Overview page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#30]
#### User Story

> As an IBM.com page creator

>I need to have a good understanding of the overall patterns available to me

> so that I can: do my day to day work without confusion.

#### Additional information
- Card page on v19a website Components section can be viewed [here](https://www.ibm.com/standards/web/components/card/).
- Patterns overview page on the current Carbon Design website can be viewed [here](https://www.carbondesignsystem.com/patterns/overview)

#### Acceptance criteria
- [ ] Content and design created and reviewed with Wonil.
- [ ] Shared with the Carbon and IDL team for feedback.

**Comment by JennySanchez** [comment]
@jimpistilli The pattern overview page content is ready for review and edit. The purpose of this page is to let the adopters know what is the pattern with a high-level description of what each pattern is. The work document is saved on [BOX](https://ibm.box.com/s/9qcicnpa4qhw7xmxbyb1vcnw8o165p95).

-----

![Screen Shot 2019-11-01 at 5 05 21 PM](https://user-images.githubusercontent.com/45213839/68059593-fbd2cb80-fcca-11e9-833d-0e6e3aac5358.png)

**Comment by jimpistilli** [comment]
Hi @JennySanchez - can get going on this today but should all of the text in the Box note be reviewed or just the copy that's above in the screenshot? There's additional text it looks like in the note, some is in light grey.  All of it?  Thanks

**Comment by JennySanchez** [comment]
@jimpistilli Only the copy in the screenshot. Thank you for confirming.

**Comment by jimpistilli** [comment]
@JennySanchez here's a version with light edits, as the substance looks fine to me:

https://ibm.box.com/s/zx545syg4lensvbdr5cpd3lzfpu7yxa1

**Comment by JennySanchez** [comment]
@jimpistilli The content you have (see below) is not what I have for review and edit. Where is this from?

Let's talk in the website huddle today.

<img width="839" alt="Screen Shot 2019-11-05 at 10 08 16 AM" src="https://user-images.githubusercontent.com/45213839/68224437-3af76a00-ffb4-11e9-9db8-95426fe39203.png">

**Comment by jimpistilli** [comment]
@JennySanchez I may have taken the wrong source. On the Box note I was looking for copy and paste friendly text instead of retyping everything manually, I saw the link below that I thought was the same. I'm guessing that is not the proper source?  

https://www.carbondesignsystem.com/patterns/overview/

**Comment by jimpistilli** [comment]
@JennySanchez This link from the Note here 
![CapturFiles-Nov-05-2019_11 28 41](https://user-images.githubusercontent.com/32171262/68226117-7fd4ce00-ffbf-11e9-8215-09f94f62edd5.jpg)

**Comment by jimpistilli** [comment]
@JennySanchez @jacobottesen-dgc Hey there here is a new edited version of the correct text: https://ibm.ent.box.com/file/551575566040

As always I recommend viewing on Word over Box to see what changes were done

**Comment by JennySanchez** [comment]
The content looks great. Thanks @jimpistilli.

**Comment by JennySanchez** [comment]
*Task update:* Page created via markdowns (see below), waiting on pull request merging to the master branch for now.

---

title: Page Title
description: Lorem Ipsum
title: Patterns
description: In Digital Design System, patterns comprise common user flows and scenarios which are too complex or too universal to be encapsulated in a single component.
---
In the Digital Design System, patterns comprise common user flows and scenarios which are too complex or too universal to be encapsulated in a single component. Individual patterns often include two or more components from the system or apply to multiple components independently.
The patterns library is constantly growing, and the Digital Design core team encourages contributions of UX patterns which can apply to a broad set of Digital Design System adopters.
<br />
## Resources
<Row className="resource-card-group">
<Column colMd={4} colLg={4} noGutterSm>
   <ResourceCard
     subTitle="IBM.com Pattern React Storybook (experimental)"
     aspectRatio="2:1"
     actionIcon="arrowRight"
     href="https://deploy-preview-78--ibmdotcom-patterns-react-experimental.netlify.com/?path=/story/leadspace--default-with-image"
     >
![React icon](/images/react-icon.svg)
 </ResourceCard>
</Column>
</Row>
| Expressive patterns                            |                                                                                                              |
| ---------------------------------------------- | ------------------------------------------------------------------------------------------------------------ |
| [Cards](/patterns/cards)     | Cards are a highly flexible component for displaying a wide variety of content, including informational, getting started, how-to, next steps, and other types of content. Digital Design ships basic cards structure that responds to the grid.  |
| [Leadspace](/patterns/leadspace)   | Leadspace is the first full-width section below the masthead and is optional. Leadspaces typically include a stylized background, headline, and a call to action (CTA). This section engages visitors to sign up, submit information, search for, or purchase something.                                       |
| [Page layout](/patterns/page-layout)               | Page layout is create by using a simple grid system and simple layouts derived from it, user experience can be vastly improved through lighter experience & content, and stronger consistency through the user’s journey.                       |

**Comment by JennySanchez** [comment]
Content created and can be viewed [here](https://carbon-for-ibm.netlify.com/patterns).
