### ISSUE TITLE
Edit page option on Cupcake site

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/carbon-for-ibm-website#31]
Figure out how to add the Edit page option on live Cupcake site

**Comment by JennySanchez** [comment]
@jacobottesen-dgc I believe @jeffchew completed this task in Sprint 21 already?
Can you confirm if this feature is what you are talking about?

Link to view the actual live pages: https://carbon-for-ibm.netlify.com/

---

![Screen Shot 2019-11-07 at 10 37 50 AM](https://user-images.githubusercontent.com/45213839/68408275-b2f79880-014a-11ea-9bad-144d6ecfe50a.png)

**Comment by jeffchew** [comment]
Yes that's correct! I'll pull it into the sprint to capture the work.

cc: @RobertaJHahn
