### ISSUE TITLE
Publish approved content with markdowns (group one)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#33]
#### User Story

> As an Cupcake website creator

> I need to: publish the content with markdowns

> so that I can: work with efficiency and review the content with others with live URL

#### Additional information
- Gatsby's website set up for markdown work can be viewed [here](https://carbon-for-ibm.netlify.com/).
- The pages ready to go are: `Help`, `Resources`, `Get Started - Overview`, `Get started - designing`, and `Get started - coding`.

#### Task
- Collaborate with Jeff and Jenny for the content creation.

#### Acceptance criteria
- [x] Content and design created and reviewed with the Jenny and Wonil.
- [ ] Content and design accepted by Wonil and Linda.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Please use the content in the Sketch file I shared and went over with you today. Let me know if you have any questions. Thank you.

**Comment by jacobottesen-dgc** [comment]
UPDATE:
Pages merged to Master Branch

Merged: Get Started Overview – https://carbon-for-ibm.netlify.com/getting-started
Not Merged: Get Started Designing –
Merged: Get Started Coding – https://carbon-for-ibm.netlify.com/getting-started/coding
Merged: Resources – https://carbon-for-ibm.netlify.com/resources
Merged: Help – https://carbon-for-ibm.netlify.com/help

**Comment by JennySanchez** [comment]
@wonilsuhibm Please take a look at the published page listed above and let us know if you spot something we need to make changes with. 

FYI - there are vertical spacing issues and Jeff is working on the fix.

**Comment by wonilsuhibm** [comment]
Thank you. You guys got so much done already!!!

A few comments

### Get started overview

- The part under *Introduction* about this being controlled adoption, we may need to come up with a way to make this way more visible.

- I think there may be some questions around the *What is in Carbon for IBM.com?* section. One being are there different components and patterns for Carbon for IBM.com? What are the differences?

### Get started coding
Carbon for IBM.com

Regarding this part:
```
Carbon for IBM.com provides front-end developers and engineers a collection of reusable components to build websites and user interfaces quickly and efficiently. Adopting the library enables developers to use consistent markup, styles, and behavior in prototype and production work.
```

We may want to consider adding a quick language around our components being based on Carbon.

**Comment by jacobottesen-dgc** [comment]
Page progress


Get Started – Overview 

https://deploy-preview-91--carbon-for-ibm.netlify.com/getting-started

Progress: completed 

———

Get Started – Designing

https://deploy-preview-91--carbon-for-ibm.netlify.com/getting-started/designing

Progress: 

- Still need content from Olivia based on the public vs limited 

———

Get Started – Coding

https://deploy-preview-91--carbon-for-ibm.netlify.com/getting-started/coding

Progress:

- Need correct link for “Try React components with CodeSandbox.”

———

Resources

https://deploy-preview-91--carbon-for-ibm.netlify.com/resources

Progress:

- Still need IBM.com Pattern React Storybook (experimental) 
- Still need link to “White theme”
- Drupal icon needs to be transparent 

———

Help

https://deploy-preview-91--carbon-for-ibm.netlify.com/help

Progress:

- “Github” needs link

cc. @JennySanchez
