### ISSUE TITLE
Cupcake website page creation - Contributions/Overview page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#35]
#### User Story

> As an IBM.com page creator

> I need to: know how to contribute back to the Digital Design System

> so that I can: make contributions without confusion.

#### Additional information
Carbon's Contribution overview page can be viewed [here](https://www.carbondesignsystem.com/how-to-contribute/overview).

#### Acceptance criteria
- [x] Content and design published with markdowns.
- [x] Content and design reviewed with Jenny and Wonil.
- [x] Content and design accepted by Wonil and Linda.

**Comment by jacobottesen-dgc** [comment]
@JennySanchez Here is the markdown live on the site: https://deploy-preview-96--carbon-for-ibm.netlify.com/contributions

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Thank you and I will take a look today.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc 

### The links for the Introduction section:

- Ask a question: https://github.com/carbon-design-system/ibm-dotcom-library/issues/new?labels=question&template=question.md
- Report a bug: https://github.com/carbon-design-system/ibm-dotcom-library/issues/new?assignees=emerson-pereira%2C+jacobottesen-dgc&labels=bug&template=bug_report.md
- Request a feature: https://github.com/carbon-design-system/ibm-dotcom-library/issues/new?assignees=emerson-pereira%2C+jacobottesen-dgc&labels=Feature+request&template=feature_request.md&title=

### The link to the Contribution.md - https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/.github/CONTRIBUTING.md

Please let me know if you have any other questions with the edits we went over today.

**Comment by JennySanchez** [comment]
Hi @jacobottesen-dgc 

We need to update the text link in the last section from the "Contribution Guide"  to "Contribution Guidelines".

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Update completed.

**Comment by JennySanchez** [comment]
Preview link: https://deploy-preview-105--carbon-for-ibm.netlify.com/contributions/

**Comment by JennySanchez** [comment]
@jeffchew @wonilsuhibm Can you take a look at the content on the [Contribution page](https://deploy-preview-105--carbon-for-ibm.netlify.com/contributions/) and let Jacob and I know if we need to make any edits? Thank you.

**Comment by JennySanchez** [comment]
@jimpistilli Please take a look at the content and let us know if we need to update anything. Thank you.

**Comment by jimpistilli** [comment]
Edited version here: https://ibm.box.com/s/gow7ntre745fo1iw9qcw9q3q7vdyujmg

cc: @JennySanchez @jacobottesen-dgc

**Comment by JennySanchez** [comment]
Thank you, @jimpistilli !

**Comment by JennySanchez** [comment]
Thank you, @jimpistilli. I will take a look and let you know if I have any questions.

**Comment by JennySanchez** [comment]
@wonilsuhibm @ljcarot 
Contribution overview page content update completed and can be viewed [here](https://carbon-for-ibmdotcom.netlify.com/contributions).

**Comment by ljcarot** [comment]
Looks good to me @JennySanchez @jacobottesen-dgc
