### ISSUE TITLE
Publish approved content with markdowns (group two)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#36]
#### User Story

> As an Cupcake website creator

> I need to: publish the content with markdowns

> so that I can: work with efficiency and review the content with others with live URL

#### Additional information
- Gatsby's website set up for markdown work can be viewed [here](https://carbon-for-ibm.netlify.com/).
- The pages that need to create or publish are: `Components - Overview`, `Components - Masthead`, and `Components - Footer`.

#### Task
- Collaborate with Jeff and Jenny for the content creation.

#### Acceptance criteria
- [x] Content and design created and reviewed with the Jenny and Wonil.
- [ ] Content and design accepted by Wonil and Linda.

**Comment by JennySanchez** [comment]
@RobertaJHahn FYI, the story points are reduced because we have a fewer page for Jacob to publish for this task.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Can you update the left navigation - Layout Patterns section to match the list below? The page title should match the nav listing as well.

- Overview
- Content array
- Lead space
- Simple long form
- Use cases

**Comment by JennySanchez** [comment]
@jacobottesen-dgc 
Note: Reach out to Lara for footer Anatomy section.

**Comment by jacobottesen-dgc** [comment]
@JennySanchez Just finishing updating the menu nav

Live link: https://deploy-preview-111--carbon-for-ibm.netlify.com/patterns

**Comment by wonilsuhibm** [comment]
@wonilsuhibm adding myself to this issue. WIll add the anatomy around the footer.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc We need to add L0 variations to the [Masthead](https://carbon-for-ibm.netlify.com/components/masthead/) page - FYI.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc This is the spec file from Wonil. We need to update the Masthead page/Spec image.

[Component Examples --wonil-s--proposal--1.1.0.sketch.zip](https://github.com/carbon-design-system/carbon-for-ibm-website/files/3928123/Component.Examples.--wonil-s--proposal--1.1.0.sketch.zip)

**Comment by JennySanchez** [comment]
**Task update:** 
- The Footer page is published and can be viewed [here](https://carbon-for-ibmdotcom.netlify.com/components/footer/).
- The Masthead page is published but have image and content update work need to be done in Sprint 24. Task issue for the update is #152
