### ISSUE TITLE
Cupcake website - Content assessments (group one)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#49]
As a Cupcake website content creator, I need to collaborate with a content designer to make sure the content on the website meets our user needs, has a consistent voice and tone across the website, and with no typos.

**For Sprint 22, we will collaborate on the following tasks:**
(Note: the list might be changed based on the user needs)

- Publish approved content with markdowns (group one) #33 
- Cupcake website page creation - Guidelines/Overview page #15

**Comment by JennySanchez** [comment]
@jimpistilli I believe there's nothing else you need to do for this task. Please confirm and let me know if there's anything Jacob and I missed.

**Comment by jimpistilli** [comment]
Confirmed!
