### ISSUE TITLE
Cupcake website – collate and update lead space documentation 

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/carbon-for-ibm-website#57]
#### User Story

> As an IBM.com page creator

> I need to: have a good understanding of the components, patterns, etc

> so that I can: do my day to day work without confusion.

#### Task
- Lara to gather and update all `lead space` pattern assets and guidelines.
- Collate into a document(s) for Jenny to use for content creation 
- Create and provide any assets needed for guidelines page (images, examples etc)

#### Acceptance criteria
- [x] Content addressed the needs of issue #28

**Comment by larahanlon2** [comment]
FYI @JennySanchez

**Comment by larahanlon2** [comment]
@JennySanchez @jacobottesen-dgc still working through this doc but take a look at the leadspace guidelines so far, [here](https://ibm.ent.box.com/notes/528552262380). If you have any questions let me know!

**Comment by JennySanchez** [comment]
Looking good and thank you for the update, Lara.

**Comment by larahanlon2** [comment]
@wonilsuhibm @JennySanchez @jacobottesen-dgc 

Hey! Could you all take a look at [the guidelines](https://ibm.ent.box.com/notes/528552262380) and suggest any changes/ask questions if things are not clear. Please and thanks.

**Comment by JennySanchez** [comment]
@larahanlon2 The content is coming along nicely!

**A few questions:**

- I see you use "Leadspace" in the content, so are we using Leadspace for the pattern naming from this point on? Or the pattern is Lead Space, but the section of a page is Leadspace? (Sorry, I know we had this discussion for so many times)
- Is the content using bullet points and dashes different in the content level setup?
![Screen Shot 2019-11-18 at 1 52 55 PM](https://user-images.githubusercontent.com/45213839/69085425-9e00ec00-0a0b-11ea-966a-beb8a7a4fa80.png)

- Do you have an image folder or sketch files for images (visual reference) in this document?
- For the Call to action section, should the last example be "— Download"? 
![Screen Shot 2019-11-18 at 1 56 35 PM](https://user-images.githubusercontent.com/45213839/69085458-aeb16200-0a0b-11ea-8bd2-791065e97478.png)

**Comment by larahanlon2** [comment]
@JennySanchez Thank you!

1. If we're using `leadspace` as one term/word as per Jim's comment then we need to use it everywhere. So the name of the pattern and design documentation would be `leadspace` not `Lead space`. Let's get a final final direction on this!

2. Content bullets and dashes are no different. This is just an error in how I pasted or edited in Boxnote but feel free to update these as per the site and Gatsby theme standards!

3. Yep, I created a [this folder](https://ibm.box.com/s/rkbx8g5dowubf3e49exww7m7lu6agtob) in the **05 Patterns** folder for all images and assets related to this leadspace. It's a bit of a mess right now as I'm working through the guidelines but I'll clean it up.

4. So it may not always make sense to just have "Download" on it's own but I totally see your point. Maybe we remove this example or just take out "smartpaper", I can make a change.

**Comment by JennySanchez** [comment]
@larahanlon2 

1. Sounds good. Maybe start a Slack conversation thread? Let's get Jill involved with this conversation as well.

2. Got it.

3. Sounds good.

4. I like the idea of taking out "smart paper".

**Comment by larahanlon2** [comment]
I think we need to create a new issue dedicated to content and copy review of all of this by Jim and Jill. @wonilsuhibm what do you think?

**Comment by wonilsuhibm** [comment]
Thank you @JennySanchez and @larahanlon2 . added some comments and suggestions.

**Comment by wonilsuhibm** [comment]
@JennySanchez how are you planning to review contents with Carbon?

**Comment by JennySanchez** [comment]
@wonilsuhibm I think we can do it in the weekly design check-in meeting (preferred option) with Carbon or schedule a review session the first week of December because we should have a good amount of content to share and get feedback by then.

What do you think?

**Comment by larahanlon2** [comment]
Closing this issue. Documentation is complete as per scope of this story. Will open a new issue for review and final approval of content.
