### ISSUE TITLE
Cupcake website content assessments: Get Started Intro copy creation

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#59]
>  As a Cupcake website content creator

> I need to: collaborate with a content designer to create content for the introduction session

> so that adopters can: find the goals and reasons why we have the cupcake website.

#### Additional information
- Our current Get started intro content can be viewed [here](https://carbon-for-ibm.netlify.com/getting-started).
- We need to craft a paragraph based on the "Goals" for the cupcake website and added to the introduction section.
- Carbon's introduction content for reference and inspiration:
"The goals of the design system include improving UI consistency and quality, making the design and development process more efficient and focused, establishing a shared vocabulary between designer and developer, and providing clear, discoverable guidance around design and development best practices."

#### Task
- Collaborate with Jenny for content creation.

#### Acceptance criteria
- [ ] Content reviewed with Jenny.
- [ ] Content updated on the live website.

**Comment by JennySanchez** [comment]
@jimpistilli I am not sure how long the task will take for you to complete, please feel free to adjust the story points and let Roberta know. Thanks.

**Comment by jimpistilli** [comment]
@JennySanchez @jacobottesen-dgc Here there, below is a version with suggested edits and notes:  https://ibm.box.com/s/yzcio40njbtn258kgoesj3z25u88rtri

**Comment by JennySanchez** [comment]
@jimpistilli Thank you for the edit. We are good to go!
