### ISSUE TITLE
Create a Cupcake website page inventory list for the Carbon website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#64]
#### User Story

> As a Cupcake website creator

> I need to: a list of the pages we need to implement to the current Carbon website 

> so that I can: use it for publishing priority alignment in our team and discussion with the Carbon Team.

#### Task
- Jenny to create a list of the website pages we need to implement the current Carbon website.

#### Acceptance criteria
- [ ] List items agreed by Wonil and Scott.
- [ ] List addressed the needs for Scott to work on the IA with Jan.

**Comment by JennySanchez** [comment]
**Note:** The current Patterns roadmap can be viewed [here](https://github.ibm.com/webstandards/patterns/wiki/Learn-page-layout-pattern-roadmap).

**Comment by JennySanchez** [comment]
@wonilsuhibm @ScottBokma An initial list for us to get started below. Please take a look and let me know what do you think and if anything you can think of to be added.

---


### Without thinking about the Carbon IA. The list below is what we need to migrate over to the Carbon website:

**Home/Landing page**

**Get Started**
- Overview
- Designing
- Coding

**Guideline**
- Overview

**Components**
- Overview
- Footer
- Masthead

**Patterns**
- Overview
- Simple long form without media
- Simple content array (formerly list section)
- Sticky Table of Contents
- Use cases
- Cards without images
- Lead space, centered 
- Content array with pictograms
- Content array with cards
- Cards with images
- Featured link

**Contributions**
- Overview

**Help**
- Overview
- FAQ

-------
### With Carbon IA in mind and in the scenario of having Carbon for IBM.com tab on the left navigation:

`Carbon.com` > `Carbon for IBM.com`

**Get Started**
- Overview (focus on address the differences between Carbon and Carbon for IBM.com. When and who should use Carbon for IBM.com).
- Designing
- Coding

**Guideline**
- Overview

**Components**
- Overview
- Footer
- Masthead

**Patterns**
- Overview
- Simple long form without media
- Simple content array (formerly list section)
- Sticky Table of Contents
- Use cases
- Cards without images
- Lead space, centered 
- Content array with pictograms
- Content array with cards
- Cards with images
- Featured link

**Contributions**
- Overview

**Help**
- Overview
- FAQ

-------

### With Carbon IA in mind and what we have in the latest sitemap. For the scenario of Carbon for IBM.com content will live under the current structure:

(maybe in a tab structure within the existing page).


📎 **Add appropriate "Carbon for IBM.com" information to the "Home" page on the Carbon website based on the current structure or a total redesign.**

📎 **Add Carbon for IBM.com "Get Started" content to the "Get Started" page on the Carbon website** (Focus on address the differences between Carbon and Carbon for IBM.com. When and who should use Carbon for IBM.com).

📎 **Add Carbon for IBM.com "Designing"  content to the "Designing" page on Carbon website**

📎 **Add Carbon for IBM.com "Coding" content to the "Coding  page" on Carbon website**

📎 **Add Carbon for IBM.com specific "Guidelines" content to the Guidelines section on Carbon website**

📎 **Add Carbon for IBM.com "Footer" and "Masthead" content to the Components section on Carbon website**

📎 **Add Carbon for IBM.com "Layout Patterns (listed below)" to the "Patterns" section on Carbon website**

Layout Patterns might need to have its section.

`Carbon.com` > `Layout Patterns` 
(the same level as Patterns and rename Patterns to `Product Patterns`?)

- Overview (Focus on address what is Layout Patterns and when should use it).
- Simple long form without media
- Simple content array (formerly list section)
- Sticky Table of Contents
- Use cases
- Cards without images
- Lead space, centered 
- Content array with pictograms
- Content array with cards
- Cards with images
- Featured link

📎 **Add Carbon for IBM.com Contribution information to the "How to contribute" section on Carbon website**

📎 **Add Carbon for IBM.com Help information to the Support page on Carbon website**

📎 **Add Carbon for IBM.com FAQ information to the FAQ page on Carbon website**

📎 **Add "Expressive Theme Design Kit" link to the left navigation on Carbon website**
(Carbon's design kit link might need to be renamed to `Productive Theme Design Kit`?)

**Comment by JennySanchez** [comment]
For the right-hand side menu, we also need to add IBM Journey System and IBM Accessibility.
![Screen Shot 2019-11-18 at 1 48 32 PM](https://user-images.githubusercontent.com/45213839/69084567-22526f80-0a0a-11ea-81c1-a2cddbe1609a.png)

**Comment by ScottBokma** [comment]
Question about these patterns:
    Cards with images
    Cards without images
    Content array with cards
    Content array with pictograms

Would these be more accessible to user if all their information was located in one area for users to see the differences quickly? Not forcing user to jump to two different area to see which one is the right one to use.

Merging these patterns to be:
    Cards
    Content array

**Comment by JennySanchez** [comment]
Good point and agreed, Scott. I believe @larahanlon2 and @wonilsuhibm are still working on the list for Patterns. See #65 for detail.

**Comment by wonilsuhibm** [comment]
With Carbon IA in mind, should the IBM.com components (masthead, footer) go under Components or a separate section dedicated to IBM.com library? The same may apply to other pages like getting started, guideline / overview, etc.

**Comment by wonilsuhibm** [comment]
Thank you, Jenny. Should IBM>com specific things be separate from the rest of Carbon? More under a dedicated section?

**Comment by JennySanchez** [comment]
That will be the option of - "With Carbon IA in mind and in the scenario of having Carbon for IBM.com tab on the left navigation:" (see above).

**Comment by wonilsuhibm** [comment]
@JennySanchez Got it! So according to that section, designing for IBM.com will be dispersed through the existing IA. Have you shown this to Carbon team?

**Comment by ScottBokma** [comment]
@wonilsuhibm I am putting something together now using the latest sitemap Jan shared with me and the work Jenny as created. As well as documenting questions I have on Jan's sitemap. Here is where I'm at currently.

![Carbon-sitemap-withDDS-mirgation](https://user-images.githubusercontent.com/53090172/69346990-beb28700-0c41-11ea-9b1e-46ca784d0341.png)

**Comment by JennySanchez** [comment]
**Next Step:** Review the options with the collaborators (Wonil, Lara, Scott, and Jacob). Review session scheduled for 11-22 (Friday).

**Comment by JennySanchez** [comment]
Based on the review today below will be the inventory list for us to start the conversation with the Carbon Team. Once we have a clear direction on the IA, we will update the list based on the agreed outcome with the Carbon Team.

---

**Home/Landing page**

**Get Started**
- Overview
- Designing
- Coding

**Guideline**
- Overview

**Components**
- Overview
- Footer
- Masthead

**Patterns**
- Overview
- Simple long form without media
- Simple content array (formerly list section)
- Sticky Table of Contents
- Use cases
- Cards without images
- Lead space, centered 
- Content array with pictograms
- Content array with cards
- Cards with images
- Featured link

**Contributions**
- Overview

**Help**
- Overview
- FAQ
