### ISSUE TITLE
DGC Design Townhall presentation for Cupcake Website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#94]
![Screen Shot 2019-11-22 at 2.52.43 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/f132b08b-d73a-4d74-adca-eb3a31ce13e0)

**Comment by JennySanchez** [comment]
The demo window is a major improvement for the user experience improvement.  I think we should touch on this in the town hall meeting.

**Comment by JennySanchez** [comment]
Wonil, For the website, I am thinking of showing three pages that have a new feature or dramatically helping adopter pain points compare to the v19a website.

---

- Components overview page. Adopters now can see all the components we offer in the design kit in one place and know what they look like.
![Screenshot_2019-11-27 Overview](https://user-images.githubusercontent.com/45213839/69741273-60cde580-1100-11ea-94d0-32c9d0116c7c.png)

- Components Demo window. Adopters no longer need to scroll up and down the website page to find information. They can also view the components within different themes.
![Button - updated](https://user-images.githubusercontent.com/45213839/69741304-70e5c500-1100-11ea-8a8f-fb24099db533.jpg)

- Resources page. Adopters now have one central place to find all the resources they need to get started, get help and more.
![Resources - v2](https://user-images.githubusercontent.com/45213839/69741323-793e0000-1100-11ea-9bd2-8736beeb26b9.jpg)

- Help page. Adopters can find clear direction on how to find help and which channel will be the best way for hem to troubleshoot.
![Help - v3](https://user-images.githubusercontent.com/45213839/69741333-7e9b4a80-1100-11ea-8a83-92b69ccd9791.jpg)

End with - "More to come, our Layout patterns section is in work to provide valuable guidance on how to craft a functional yet beautiful IBM.com page."

**Comment by wonilsuhibm** [comment]
Hey Jenny, this sounds good to me. Should we also include a slide that covers an overview of your website strategy moving forrwad?

**Comment by JennySanchez** [comment]
Sure. I might need some help with this because we do not have a clear vision of how we are going to merge with the Carbon website or timeline around it at this moment. 

What do you have in mind?

**Comment by JennySanchez** [comment]
@wonilsuhibm The presentation slides for the cupcake website portion is attached below.
On page five and page six you will find two options to address the strategy moving forward. Please feel free to pick one and make any edits to make it work for the rest of the presentation slides.
[DGC-design-town-hall--Cupcake Website.key.zip](https://github.com/carbon-design-system/carbon-for-ibm-website/files/3918529/DGC-design-town-hall--Cupcake.Website.key.zip)
