### ISSUE TITLE
Cupcake website page content creation - Help/FAQ page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#98]
> As a Cupcake website content creator

> I need to: know what frequently asked questions our adopters have

> so that I can: consolidate them and present them on the FAQ page.

#### Additional information
- Let's create the content for the current release based on the [v19a](https://www.ibm.com/standards/web/faq.html), Carbon website [FAQ page](https://www.carbondesignsystem.com/help/faq) and input from Linda, Wonil, and Jeff.

#### Acceptance criteria
- [x] A list of the questions published with markdowns
- [x] Reviewed the list with Linda, Wonil, and Jeff.
- [x] Content and design accepted by Linda.

**Comment by jacobottesen-dgc** [comment]
@JennySanchez 

FAQ page is ready for review!

Live link: https://deploy-preview-111--carbon-for-ibm.netlify.com/help/faqs

**Comment by JennySanchez** [comment]
Our next step is to review the content with Linda and get her input on finalizing the content.

**Comment by ljcarot** [comment]
[My feedback below in red.docx](https://github.com/carbon-design-system/carbon-for-ibm-website/files/3914253/My.feedback.below.in.red.docx)

**Comment by JennySanchez** [comment]
@ljcarot Thank you for reviewing and making edits to the FAQ page content. It makes sense to me and I will make updates to the page.

**Comment by JennySanchez** [comment]
@ljcarot FAQ page update completed and can be viewed on the [Cupcake website](https://carbon-for-ibm.netlify.com/help/faqs).

**Comment by JennySanchez** [comment]
@wonilsuhibm @jeffchew Please take a look and let me know if we missed anything. Thank you.
